import type { Metadata, Viewport } from "next";
import { Inter, Unbounded } from "next/font/google";
import "./globals.css";
import { SmoothScroll } from "@/components/SmoothScroll";
import { Analytics } from "@/components/Analytics";
import { CookieBanner } from "@/components/CookieBanner";
import {
  LocalBusinessJsonLd,
  WebSiteJsonLd,
  WebPageJsonLd,
  BreadcrumbJsonLd,
  ServiceJsonLd,
} from "@/components/JsonLd";
import { SITE_URL } from "@/lib/site";

const display = Unbounded({
  subsets: ["latin", "cyrillic"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-display",
  display: "swap",
});

const sans = Inter({
  subsets: ["latin", "cyrillic"],
  weight: ["400", "500", "600"],
  variable: "--font-sans",
  display: "swap",
});

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default:
      "Сонячні станції під ключ у Хмельницькому — RUNA SOLAR",
    template: "%s | RUNA SOLAR",
  },
  description:
    "Монтаж гібридних сонячних електростанцій, накопичувачів та САЖ під ключ у Хмельницькому та області. Tier-1 обладнання, гарантія до 25 років, документи 'Зеленого тарифу' включені.",
  applicationName: "RUNA SOLAR",
  authors: [{ name: "RUNA SOLAR", url: SITE_URL }],
  creator: "RUNA SOLAR",
  publisher: "RUNA SOLAR",
  category: "Renewable Energy",
  keywords: [
    "сонячні електростанції Хмельницький",
    "СЕС під ключ Хмельницький",
    "сонячні станції під ключ",
    "монтаж сонячних батарей Хмельницький",
    "гібридна сонячна станція Хмельницька область",
    "сонячні панелі Хмельницький",
    "СЕС для дому",
    "СЕС для бізнесу",
    "САЖ для дому Хмельницький",
    "накопичувачі енергії LiFePO4",
    "установки зберігання енергії",
    "резервне живлення в блекаут",
    "гібридний інвертор Deye",
    "зелений тариф 2026",
    "Tier-1 сонячні панелі",
    "RUNA SOLAR",
    "Runa Solar Хмельницький",
  ],
  referrer: "origin-when-cross-origin",
  formatDetection: {
    email: false,
    address: false,
    telephone: true,
  },
  alternates: {
    canonical: SITE_URL,
  },
  openGraph: {
    type: "website",
    locale: "uk_UA",
    url: SITE_URL,
    siteName: "RUNA SOLAR",
    title: "RUNA SOLAR — Сонячні станції, що не вимикаються разом зі світлом",
    description:
      "Гібридні СЕС, накопичувачі енергії та САЖ під ключ для дому й бізнесу у Хмельницькому та області. Tier-1 обладнання, гарантія до 25 років, документи 'Зеленого тарифу' включені.",
    // OG image auto-generated by app/opengraph-image.tsx
  },
  twitter: {
    card: "summary_large_image",
    title: "RUNA SOLAR — Сонячні станції з резервом у Хмельницькому",
    description:
      "Гібридні СЕС, накопичувачі та САЖ під ключ. Tier-1 обладнання, гарантія до 25 років.",
    // Twitter image auto-generated by app/twitter-image.tsx
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  verification: {
    google: "xiNus9JjQIqjx4zRFqGy-hF59Rf_x4OrYk0vyajVXEU",
  },
};

export const viewport: Viewport = {
  themeColor: "#FAFAF7",
  width: "device-width",
  initialScale: 1,
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="uk" className={`${display.variable} ${sans.variable}`}>
      <head>
        <LocalBusinessJsonLd />
        <WebSiteJsonLd />
        <WebPageJsonLd />
        <BreadcrumbJsonLd />
        <ServiceJsonLd />
      </head>
      <body>
        <SmoothScroll />
        <Analytics />
        {children}
        <CookieBanner />
      </body>
    </html>
  );
}
